on: [push]
jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3.10 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --no-cache-dir -r requirements.d/test.txt

  setup-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3.10 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --no-cache-dir -r requirements.d/test.txt
      - run: wget https://github.com/Bengt/BirdNET-Training-Data/archive/refs/heads/main.zip
      - run: unzip main.zip
      - run: rm -rf main.zip
      - run: venv/bin/python -m pytest tests

  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3.10 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --no-cache-dir -r requirements.d/test.txt
      - run: venv/bin/python -m pip install -e .

  build-analyze-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: python3.10 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --yes ffmpeg libgirepository1.0-dev
      - run: python3.10 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --upgrade -r requirements.d/build.in
      - run: venv/bin/python pyinstaller_analyze.py

  build-analyze-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: python3.11 --version
      - run: brew install ffmpeg cairo pkg-config gobject-introspection
      - run: python3.11 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --upgrade -r requirements.d/build.in
      - run: venv/bin/python pyinstaller_analyze.py

  build-analyze-windows-gvsbuild-source:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: choco install ffmpeg visualstudio2022-workload-vctools
      - run: |
          mkdir C:\gtk-build\github
          cd C:\gtk-build\github
          git clone https://github.com/wingtk/gvsbuild.git
          cd C:\gtk-build\github\gvsbuild
          python -m venv .venv
          .\.venv\Scripts\activate.ps1
          pip install .
      - run: gvsbuild build --enable-gi --py-wheel gobject-introspection gtk3 pycairo pygobject
      - run: deactivate

      - run: python3 -m venv venv
      - run: venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
      - run: venv\Scripts\python.exe -m pip install --upgrade -r requirements.d/build.in
      - run: venv\Scripts\python.exe pyinstaller_analyze.py

  build-analyze-windows-gvsbuild-pipx:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: choco install ffmpeg visualstudio2022-workload-vctools
      - run: python3 -m pip install --user pipx
      - run: set PIPX_HOME=C:\pipx
      - run: set PIPX_BIN_DIR=C:\pipx-bin
      - run: python3 -m pipx ensurepath
      - run: python3 -m pipx install gvsbuild
      - run: python3 -m venv venv
      - run: venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
      - run: venv\Scripts\python.exe -m pip install gvsbuild
      - run: venv\Scripts\python.exe -m gvsbuild build --enable-gi --py-wheel gtk3 pycairo pygobject
      - run: venv\Scripts\python.exe -m gvsbuild build --enable-gi --py-wheel gobject-introspection
      - run: venv\Scripts\python.exe -m pip install --upgrade -r requirements.d/build.in
      - run: venv\Scripts\python.exe pyinstaller_analyze.py

  build-gui-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: python3.10 --version
      - run: sudo apt-get update
      - run: sudo apt-get install --yes ffmpeg libgirepository1.0-dev
      - run: python3.10 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --upgrade -r requirements.d/build.in
      - run: venv/bin/python pyinstaller_gui.py

  build-gui-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: python3.11 --version
      - run: brew install ffmpeg cairo pkg-config gobject-introspection
      - run: python3.11 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --upgrade -r requirements.d/build.in
      - run: venv/bin/python pyinstaller_gui.py

  build-gui-windows-gvsbuild-source:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: choco install ffmpeg visualstudio2022-workload-vctools
      - run: |
          mkdir C:\gtk-build\github
          cd C:\gtk-build\github
          git clone https://github.com/wingtk/gvsbuild.git
          cd C:\gtk-build\github\gvsbuild
          python -m venv .venv
          .\.venv\Scripts\activate.ps1
          pip install .
      - run: gvsbuild build --enable-gi --py-wheel gobject-introspection gtk3 pycairo pygobject
      - run: deactivate

      - run: python3 -m venv venv
      - run: venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
      - run: venv\Scripts\python.exe -m pip install --upgrade -r requirements.d/build.in
      - run: venv\Scripts\python.exe pyinstaller_gui.py

  build-gui-windows-gvsbuild-pipx:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: choco install ffmpeg visualstudio2022-workload-vctools
      - run: python3 -m pip install --user pipx
      - run: set PIPX_HOME=C:\pipx
      - run: set PIPX_BIN_DIR=C:\pipx-bin
      - run: python3 -m pipx ensurepath
      - run: python3 -m pipx install gvsbuild
      - run: gvsbuild build --enable-gi --py-wheel gtk3 pycairo pygobject
      - run: gvsbuild build --enable-gi --py-wheel gobject-introspection
      - run: python3 -m venv venv
      - run: venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
      - run: venv\Scripts\python.exe -m pip install gvsbuild
      - run: venv\Scripts\python.exe -m pip install --upgrade -r requirements.d/build.in
      - run: venv\Scripts\python.exe pyinstaller_gui.py

  build-gui-windows-qt:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: python3 --version
      - run: choco install ffmpeg visualstudio2022-workload-vctools
      - run: python3 -m venv venv
      - run: venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel
      - run: venv\Scripts\python.exe -m pip install --upgrade -r requirements.d/build.in
      - run: venv\Scripts\python.exe pyinstaller_gui.py
