on: [push]
jobs:
  install-requirements:
    runs-on: ubuntu-20.04
    steps:
      - run: python3.8 -m venv venv
      - run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - run: venv/bin/python -m pip install --no-cache-dir -r requirements.d/requirements.txt
